### ISSUE TITLE
Otsikoiden erottuminen <h1>

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#10]
Moi,

otsikot erottuvat yhden luvun sisällä mielestäni vähän huonosti. Olisiko niiden visuaalista ilmettä mahdollista parannella jotenkin niin, että nousisivat paremmin esiin? Ne ovat kuitenkin aika tärkeitä sisällön rakenteen kannalta.

**Comment by ruumis** [comment]
Onko parempi?
http://kisallioppiminen.fi/kurssit/vektorit_versio0/xy-taso/index.html

**Comment by LottaOinonen** [comment]
On parempi, mutta samalla tehtävien otsikkopalkkien korkeus kasvoi : / Niiden osalta vanha oli parempi.

**Comment by ruumis** [comment]
hups, korjattu. muutanko nyt tuollaiseksi?

**Comment by LottaOinonen** [comment]
Mun puolesta joo :)
