### ISSUE TITLE
Geogebra-kuvia suoriin ja tasoihin

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#12]
Listassa kuvan nimi ja kuvailu
- L4k1: pisteet A ja B sekä niiden kautta kulkeva suora
- L4k2: piste A ja muutamia suoria, jotka kulkevat sen kautta
- L4k3: piste O, piste A, pisteen A kautta kulkeva suora, vektori OA, suoran jokin suuntavektori v pisteestä A alkaen
- L4k4: kopio edellisestä kuvasta paitsi v:n sijaan tv (suuntavektorin jokin skalaarimonikerta); lisäksi näkyviin piste P ja vektori OP
- L4k5: voi olla vaikea geogebralla(?): pisteet A, B ja C ja taso, joka näyttää kulkevan niiden kautta
- L4k6: pisteet A, B ja C samalla suoralla ja muutama taso niiden kautta (vaikea?)
- L4k7: piste A, sen kautta kulkeva taso ja kaksi tason ei-yhdensuuntaista suuntavektoria (vaikea?)

Mä voin tehdä Tikzillä nuo tasokuvat, jos ovat vaikeita geogebralla.

**Comment by LottaOinonen** [comment]
Ai niin, mihinkään yllä olevan listan kuvaan ei koordinaatistoa mukaan

**Comment by LottaOinonen** [comment]
Yksi kuva unohtui:

L4t3bk: tasokoordinaatisto ja siinä suora, joka ei kulje origon kautta (tulee siihen tehtävään)

**Comment by pnissine** [comment]
Ensimmäiset versiot tehty.

**Comment by LottaOinonen** [comment]
Moi, laittaisitteko nuo kuvat kansioon kurssit/.../suoratJaTasot/img jonka pitäisi löytyä tän projektin hakemistopolusta? Saisin ne sitten Githubin kautta. FB pakkaa ne postimerkin kokoisiksi..

**Comment by pnissine** [comment]
Kuvatiedostojen lisääminen ei taida onnistua netti-githubin kautta. Laitan kuvat siksi nyt sähköpostilla tulemaan ja latailen desktop-version huomenna tai viimeistään perjantaina.

**Comment by LottaOinonen** [comment]
Kiitos kuvista! Huomasin kuitenkin pari tarvittavaa täydennystä, jotka johtuivat lähinnä omista epäselvistä ohjeistani:

L4k7: piste A, sen kautta kulkeva taso ja kaksi tason ei-yhdensuuntaista suuntavektoria on OK, mutta pitäisi lisätä vektoreille nimet v ja w ja lisäksi näkyviin origo O ja paikkavektori OA (nimettyinä). Näin tämä kuva on linjassa parinsa L4k3 kanssa.

L4t3bk: tasokoordinaatisto ja siinä suora, joka ei kulje origon kautta (tulee siihen tehtävään) on muuten OK, mutta suora on vähän liian "vaikea" koska kulkee vain yhden Z x Z pisteen kautta. Voisi laittaa jonkin helpomman, jossa järkeviä paikkavektorin valintoja olisi mahdollista tehdä useita erilaisia.

Lisäksi voit laittaa sen geogebrademon paikalleen, jos menee helposti. Mulla on opetusta ja palavereja Kumpulassa klo 10-14, joten en hetkeen koske ainakaan näihin suoriin ja tasoihin.

**Comment by pnissine** [comment]
Toimiiko nyt?

Piia

**Comment by pnissine** [comment]
Tein geogebrademon ja laitoin sivulle, nyt siinä ei ole yhtälöä, katsotaan, tarvitseeko ja opettelen sen vielä.

**Comment by LottaOinonen** [comment]
Demo on mahtava, mutta en löydä niitä uusia kuvia

**Comment by pnissine** [comment]
Oli mennyt githubin postiin ja sinnehän ei liitteet mene, laitoin sinun Gmail-postiisi. Lähetin puhelimen kautta, jos koko meni liian pieneksi niin täytyy laittaa myöhemmin kotoa uudestaan. 

Piia

Lähetetty iPhonesta
