### ISSUE TITLE
Yläpalkkien xyz-linkki vie väärään osoitteeseen

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#13]
Heips, 

yläpalkki "xyz" vie tällä hetkellä väärään osoitteeseen. Pitäisi olla xyz-koordinaatisto (ei xyz-taso).

**Comment by pnissine** [comment]
korjattu.

taika tapahtuu täällä:
https://github.com/kisallioppiminen/kisallioppiminen.github.io/blob/master/_data/topbar/maa4.yml
