### ISSUE TITLE
Vektoreiden nimet kuvissa?

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#16]
Mietin, että toimiiko esim. tehtävässä 15 tuo, että opiskelijat nimeävät vektorit itse, vai pitäisikö vektorit nimetä valmiiksi? Mitä mieltä olet, Piia?

**Comment by LottaOinonen** [comment]
Tarkoitin siis xy-tason tehtävää 15

**Comment by LottaOinonen** [comment]
Sama tehtävässä 19

**Comment by pnissine** [comment]
Minusta toimii noinkin, kun ensimmäinen kohta on, että nimeä. Se tuli mieleen tehtävästä 19, että pitäisikö siinä lisäksi pyytää merkitsemään samansuuntaisuus ym. yllä esitetyillä merkinnöillä, jotta ne tulisivat myös tutuiksi. Jos eivät kertaakaan käytä, niin saattaa jäädä vieraaksi jossain myöhemmässä tehtävänannossa, jos siellä esim. yhdensuuntaisuus ilmoitettu muodossa a||b. 

Pääasia minusta on, että he ymmärtävät, mitä kuvasta etsivät, mutta sen verran merkinnöistä pitää minusta vaatia, etteivät niitä säikähdä kovasti, jos tekstin seassa sellainen on.

**Comment by LottaOinonen** [comment]
Joo, totta. Mietin vain, että tuleeko hankaluuksia, jos kaikki nimeävät eri tavoilla, ja haluttaisiin keskustella yhdessä.. Ja toisaalta, oletammeko, että he kopioivat kuvan vihkoonsa? Muuten voi olla vaikea nimetä (ja ainakin omista opiskelijoistani osa on laiskoja..). 

Tarkoitus ei ole jankata vastaan, vaan ajatella ääneen.. :)

**Comment by LottaOinonen** [comment]
Lisätään tuo samansuuntaisuusmerkintä

**Comment by pnissine** [comment]
No se on totta, tuo keskustelu ja ehkä erityisesti tuo kesto, jos kopioivat kuvasta lähtien, mikä välttämätöntä jos halutaan että nimeävät. Lisäarvoa kuitenkaan tuossa tehtävässä kuvan kopioiminen ei minusta anna. Kannatti siis ajatella ääneen, kannatan sittenkin nimiä suoraan näkyviin ja näin keskitytään tehtävässä olennaiseen :)

**Comment by pnissine** [comment]
Ja seuraavaan kohtaan vastakkaissuunta?

**Comment by LottaOinonen** [comment]
Joo, siellä on nyt yksi versio, jos haluat kurkata

**Comment by pnissine** [comment]
Juuri noin. Ja sitten kuvan muokkaus niin, että nimet näkyvissä?

**Comment by LottaOinonen** [comment]
Kuvat on nyt muokattu

**Comment by pnissine** [comment]
On parempi noin! Huomasin painovirheen: tehtävän 19 kuvassa 4j vektorissa ei ole vektorin viivaa j:ssä. 

Lähetetty iPhonesta
