### ISSUE TITLE
Kahden pisteen välinen vektori

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#17]
Moi, tein uutta versiota kahden pisteen välisen vektorin osuudesta. Se vaatii ehkä vielä prosessointia, mutta mielelläni kuulisin, mitä ajatuksia sinulle siitä tulee, ennen kuin jatkan sen työstämistä.

**Comment by pnissine** [comment]
Näyttää hyvältä! Sitä mietin, että haluatko, että opiskelijat jatkossa aina muodostavat kahden pisteen välisen vektorin paikkavektoreiden avulla vai alkavatko he jossain kohti tehdä sitä idealla päätepisteen x-koord. - alkupisteen x-koord. Jos alkavat, niin tällöin kaipaisin vielä vektorin AB sieventämiseen yhtä riviä, jossa tämä muoto tulisi näkyviin, eli (3-(-3))i+(3-1)j=6i+2j.

**Comment by LottaOinonen** [comment]
Joo, mietin, että tuosta loppup-alkup. voisi tehdä ihan oman tehtävänsäkin.. Eli antaisi tuon olla noin, ja sitten jatkaisi vielä hiukan sepustusta ja yksi tehtävä tuosta ideasta.

Yritän tehdä senkin tässä lähiaikoina

**Comment by pnissine** [comment]
Sekin sopii.
