### ISSUE TITLE
Lotan ToDo xy-taso

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#18]
- Komponentteihin jako: lisää selitystä ja tehtäviä
- Lisää kuva, jossa katsotaan kuvasta vektorien välisiä kulmia
- Janan jako suhteessa -tehtävä paikkavektorin kohtaan
- Katso läpi tehtävät

**Comment by LottaOinonen** [comment]
Komponentteihin jako voisi ehkä olla xy-tasossa aika kevyesti ja laskennallisemmin xyz-koordinaatisossa. Eka versio on valmis, jos haluat katsoa. Yksi tehtävä luuppi 0:ssa ja tällä hetkellä yksi tehtävä luupissa 1, molemmat kuvasta päättelemällä. 

Mulla on idea tuohon janan jako suhteessa -juttuun, yritän pistää nettiin vielä tänään, samoin tuon kuvan liittyen vektoreiden väliseen kulmaan.

Piia, saatko nämä viestit sähköpostiin, vaikka et olisi "assignee"?

**Comment by pnissine** [comment]
Komponentit näyttävät hyvältä ja minusta tuo tehtävämäärä riittää xy-tasossa. Idea, että xy-tasossa vain kuvan avulla, on hyvä. Toisaalta kuvasta voi olla iloa laskennallisessakin puolessa, jotta uskoo, että löydetyt luvut ovat todella oikeat, mutta sellaisen tehtävän voi hyvin teettää xyz-koordinaatistossa, vaikka olisikin tason vektoreilla.

Sähköposti taitaa tulla vain, jos on assigned.

Hyvä jos ideaa jakosuhteeseen, toisaalta kuuluu sarjaan ei niin olennaista, joten väkisin sitä ei tarvitse saada mukaan. Tein silloin perjantaina sen yhden jakosuhdetehtävän, näytti olevan tällä hetkellä nro 68. 

Pari tehtävää näytti olevan nyt piilotettuna tehtäväsarjassa, mutta ne on nopea muuttaa. 

Lähetetty iPhonesta

**Comment by LottaOinonen** [comment]
Nyt on tehty kaikki muu paitsi tehtävien kattavuuden tarkastus. Päivityksiä:
- paikkavektorin kohdalla on pohjustusta jakosuhdetehtäviin
- vektorien välisen kulman kohdalla on sellainen kuvatehtävä, josta oli puhetta.

Mun mielestä olisi tärkeä katsoa vielä tehtävät huolella ja merkitä muistiin, jos sieltä puuttuu jonkin oleellisen taidon harjoittelu tai jos jostain aiheesta on liikaa liian helppoja / vaikeita tehtäviä. Aikataulullisesti olisi varmaan parasta, jos sinä Piia tekisit tällaisen tsekkauksen jossain välissä. Mä siirryn huomenna naputtamaan kasaan xyz-koordinaatistoa. Tämä xy-taso kun vihdoin alkaa olla kasassa :)

**Comment by LottaOinonen** [comment]
Ai niin, korjasin ne piilossa olleet tehtävät näkyviin. Kopiointivirheitä, hyvä että huomasit! :)

**Comment by LottaOinonen** [comment]
Siis huomasit..

**Comment by LottaOinonen** [comment]
Hyvä se sun tekemä jakosuhdetehtävä!

**Comment by pnissine** [comment]
Hienoa! Kuvatehtävä on kivaa perustreeniä ja jos joku ei tuosta ymmärrä, mikä on jakosuhde ja mitä se tarkoittaa, niin jo on ihme. Voin hyvin katsoa tehtävät vielä rauhassa läpi, saan varmaankin huomenna tai torstaina sen tehtyä.

Lähetetty iPhonesta
