### ISSUE TITLE
Kurssien rakene

### ISSUE THREAD

**Issue by ruumis** [kisallioppiminen/kisallioppiminen.github.io#2]
yhden kurssin sisällä tekninen rakenne on seuraava: jokainen "luku" on omassa alikansiossaan index.html-tiedostona, ja siihen liittyvät kuvat sitten omassa kansiossaan.

**Comment by ruumis** [comment]
Thomas huolehtia siitä kurssin Etusivusta, jossa ne yläpalkit ovat

**Comment by LottaOinonen** [comment]
Ylävälilehtiin tulisi ainakin tällä tietoa seuraavat luvut: 
1. Vektorit ja xy-koordinaatisto
2. Vektorit ja xyz-koordinaatisto
3. Suorat ja tasot
4. Geometriaa vektorien avulla

**Comment by pnissine** [comment]
Yläpalkit lisätty
