### ISSUE TITLE
Teoreemat ja värit

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#20]
Moi,

huomasin ulkoasun kehittyneen :) Keskitykset näyttävät hyvältä. Mietin tuota teoreemojen punaista sävyä. Ehdottaisin, että se vaihdettaisiin esim. johonkin sinisen sävyyn tms, koska punaiseen liittyy niin vahvoja sivumerkityksiä (punaiset liikkennevalot, joku "näkee punaista", kaikki kiellot ja varoitusmerkit jne.) Mulla oli tahallaan ne teoreemat harmaita, jotta ne olisivat lähempänä tavallista tekstiä kuin määritelmät. Määritelmät kun ovat oikeasti hyvin tärkeitä (sopimuksia siitä, mitä asioilla tarkoitetaan) mutta varsinkin lukiotasolla teoreemat ja perustelut ovat paljon lähempänä kirjan normaalia selitystekstiä. Monesti on ollut vähän jopa hankala arvioida, mikä asia laitetaan oikein teoreemaksi ja mikä vain selitetään tekstissä. Tämä siis perusteluna jollekin neutraalimmalle värille. Saa siis toki olla jokin muu kuin harmaa, mutta mieluusti jokin rauhoittava ja lempeä väri, esim. vaalea sininen ja sen eri sävyt.

**Comment by LottaOinonen** [comment]
Ai niin, tähän liittyen: xy-tasossa on vielä osa teoreemoista kovakoodattuna, eli ne ovat edelleen harmaita.

**Comment by pnissine** [comment]
Kannatan teoreeman väriksi myös jotain rauhallista, minusta se harmaa oli oikein mainio.

Lähetetty iPhonesta

**Comment by ruumis** [comment]
Teoreemat jälleen harmaita ja kovakoodaus poistettu.

**Comment by LottaOinonen** [comment]
Hienoa! Jos harmaa ei ole liian tylsä, mennään sillä toistaiseksi. Passaa ainakin mulle.
