### ISSUE TITLE
Kahden pisteen välinen vektori

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#21]
Kahden pisteen välinen vektori -osuus on nyt mun puolesta valmis, voit käydä kurkkaamassa. 

Vähän hitaasti on nyt taas edennyt parin päivän ajan, kun tuli vähän tilanteita muuten, mutta nyt taas sorvin ääressä, eli kyllä tämä tästä

**Comment by pnissine** [comment]
Hyvältä näyttää! Sellainen tuli mieleen, että pitäisikö vielä korostaa tuossakin kohtaa, että järjestyksellä on väliä, ts. kun sanotaan että ...koordinaattien erotus niin lisäisi joko tekstiin tai vielä tehtävän, jolla korostaisi päätepiste-alkupiste -ajatusta. 

Lähetetty iPhonesta

**Comment by LottaOinonen** [comment]
Muutin tekstiä vähän, mutta en ryhtynyt nyt tekemään tehtävää. Kuvassa oli typo, korjasin sen. Mielestäni voisi toimia noinkin, mutta luuppi 1 tarvitsee ehkä tästä vielä tehtävän.

**Comment by pnissine** [comment]
Toimii noin hyvin.

Lähetetty iPhonesta
