### ISSUE TITLE
<ol> listojen tyylit

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#22]
Moi! Mietin, olisiko mahdollista jotenkin viilailla aakkosellisten alakohtien tyyliä niin, että ne eivät olisi muotoa

a. jotain
b. jotain muuta
c. lisää

vaan

(a) jotain
(b) jotain muuta
(c) lisää.

Ne on toteutettu listoina `<ol type="a">`

**Comment by LottaOinonen** [comment]
Tämä ei ole tärkeä, mutta aina välillä häiritsee..

**Comment by pnissine** [comment]
Minä laittaisin jopa muotoon a) jne. mutta pystyn hyvin elämään muidenkin muotojen kanssa. 

Lähetetty iPhonesta

**Comment by ruumis** [comment]
laitoin nyt Lotan muotoon ja vähän suurensin kokeeksi

**Comment by LottaOinonen** [comment]
Moi, kiitos! Chromella katselin ja siinä nuo (a), (b) jne. ovat vähän hassusti ylempänä kuin rivillä oleva muu teksti. Johtuukohan suurennoksesta vain mistä?

**Comment by pnissine** [comment]
Siitä suurennoksesta olikin meillä täällä kotona puhetta, että voisi kokeilla ilman, oli vähän tarpeeton.

**Comment by LottaOinonen** [comment]
Huomasin, että nyt kaikki ol-listat ovat aakkosissa. En siis osaa enää tehdä numeroituja listoja..

**Comment by ruumis** [comment]
korjaan

**Comment by ruumis** [comment]
nyt korjattu siten, että nuo (a)-listat saa kun laittaa ol class="a" ja normaalit a-listat ol type="a"
