### ISSUE TITLE
Teoreemat ja määritelmät

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#23]
Tää on nyt tällaista viilausta, mutta pari asiaa pisti silmään tänään kun kirjoittelin:
- Teoreemat ja määritelmät voisi laittaa yhtä leveiksi keskenään (tuo eri leveys on varmaan jotain mun alkuaikojen sekoilua)
- Perusteluissa on aika paljon sisennystä, mikä pahentaa leikkautumisongelmaa puhelimella katsoessa. Ehkä niistä voisi ottaa sen sisennyksen pois?
- Teoreemat ja määritelmät menevät kiinni tehtäväboksiin, jos väliin ei kovakoodaa jotain rakoa. Pieni juttu, mutta mun silmään ei näytä niin hyvältä, jos ovat ihan kiinni toisissaan.

Ai niin vielä yksi juttu: Olisiko teoreemat mahdollista numeroida juoksevasti koko kurssin osalta?

**Comment by ruumis** [comment]
korjattu osittain. en saa repikoitua tuota viimeistä.

**Comment by LottaOinonen** [comment]
Se viimeinen (teoreema kiinni tehtäväboksissa) näkyy mulla tällä hetkellä xyz-koordinaatiston kohdassa vektoreiden pistetulo ja vektoreiden välinen kulma, pistetulon määritelmän jälkeen oleva teoreema on kiinni seuraavassa tehtäväboxissa. Mutta en tiedä, onko selainkohtainen ongelma. Mulla chrome..

**Comment by LottaOinonen** [comment]
En tiedä mitä tapahtui, mutta korjaantui äsken
