### ISSUE TITLE
Aritmeettisen summan määritelmässä termi

### ISSUE THREAD

**Issue by pnissine** [kisallioppiminen/kisallioppiminen.github.io#24]
Onko tarkoituksella, että aritmeettisen summan määritelmässä puhutaan termeistä, kun siihen asti alun maininnan jälkeen on puhuttu vain jäsenistä? Minusta se saattoi siis olla ihan valintakin, jotta molemmat sanat tulevat tutuiksi ja siksi kysyin. Toisaalta itse ehkä puhuisin määritelmissä samalla tavalla ja tehtävissä ehkä vuorottelisin.

**Comment by LottaOinonen** [comment]
Joo, tavallaan on tarkoituksena. Summan tapauksessa ei yleensä ikinä puhuta jäsenistä, vaan summassa on aina termejä. Lukujonossa on mun mielestä aina jäseniä, mutta joidenkin kirjojen mukaan myös termejä. Eli siellä lukujonossa voisi käyttää molempia sanoja, mutta summassa pitäisin vain termit.

**Comment by pnissine** [comment]
Jee, kuulostaa järkevältä.
