### ISSUE TITLE
peruslaskutoimitukset Luvut ja summat -luvussa?

### ISSUE THREAD

**Issue by pnissine** [kisallioppiminen/kisallioppiminen.github.io#25]
Mitenkäs peruslaskutoimitusten treenaaminen eri lukualueissa ja ehkä sulkeiden käytön harjoittelu tässä luvussa? Saatko ujutettua riittävästi sekaan? Yritin tehtäviin sijoittaa sekä kokonaislukuja että murtolukuja niin, että joutuvat siellä sisällä niitä miettimään, mutta tehtäviä on kovin vähän vielä sellaisesta. Kannattaako kuitenkaan hirveästi tehdäkään? 

Pitäisikö niistä kehittää tarvittaessa sellaiset "pelit", joilla voivat sitten halutessaan hinkata? Quizlet-kortit tai vain geogebra-sovellus? Jotenkin minusta äkkiseltään tuntuisi, että idea vähän menee, jos yhtäkkiä tulee 20 samanlaista tehtävää, joissa harjoitellaan aalto- ja hakasulkeita tai murtolukujen yhteen- ja vähennyslaskua. Samalla kuitenkin tuntuu, että pitäisi ehkä jotenkin mainita, että tässä näitä laskutoimituksia nyt piti harjoitella, että jos ei sujunut, niin treenaa nyt hyvä ihminen lisää.

**Comment by LottaOinonen** [comment]
Jokin pelimäinen juttu olisi kyllä hyvä. Tähän mä en osaa sanoa vielä oikein mitään järkevää, koska olen ajatellut vasta niitä lukujonoja ja summia.

**Comment by pnissine** [comment]
Siihenhän voisi tehdä myös jonkin esitietotestin pelin muotoon tai muuten vain, jolla voisivat vähän arvioida omaa tasoaan.

**Comment by LottaOinonen** [comment]
Joo, se on hyvä idea.
