### ISSUE TITLE
yhtälön ratkaisu ja sen tulkinta Lukujonoissa ja summissa

### ISSUE THREAD

**Issue by pnissine** [kisallioppiminen/kisallioppiminen.github.io#26]
Tehtävät 5,6 ja 7 johdattelevat yhtälön ratkaisuun ja siihen, mitä n on lukujonoissa. Siitä voisi kirjoittaa jotain niiden perään?

**Comment by LottaOinonen** [comment]
Tehty, jos kelpaa.. :)

**Comment by pnissine** [comment]
Jee!
