### ISSUE TITLE
Teoreemojen numerointi

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#28]
Moi,

tuli vielä mieleen tuo teoreemojen numerointi. Olisiko siihen jotain keinoa? Esim. juokseva numerointi kurssin sisällä tai luvun sisällä?

**Comment by ruumis** [comment]
tämä vaatii vähän ulkopuolista apua

**Comment by ruumis** [comment]
Sain @avihavai'lta apua. Nyt toimii juoksevana numerointina sivulla. Sen pystyisi tehdä niin, että jokaisen sivun alussa määrittelee alkuindeksin teoreemalle, sen automaattisemmaksi ei oikein tässä pysty.

**Comment by LottaOinonen** [comment]
Hienoa, riittää oikein hyvin. Se alkuindeksi sivun alussa kuulostaa hyvältä, sillä saisi juoksevan numeroinnin koko kurssiin, mikä olisi kiva. Jaksaisitko tehdä vielä sen ennen Piian kurssin alkua? Kolme ekaa lukua ovat nyt niin valmiit, että niissä teoreemojen määrä ei muutu ennen testikurssia.

**Comment by ruumis** [comment]
Onnistuu nyt lisäämällä esim.

`<input type="hidden" id="theoremStart" value="13"/>`

Sivun alkuun
