### ISSUE TITLE
Alakohtien aakkostus vielä kerran

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#29]
Moi!

Viimeistelen tuota xyz-koordinaatistoa ja huomasin, että alakohtien aakkostus (a), (b) jne. ilmeisesti jotenkin sijoittaa sen lista-elementin (a) tms. rivin ylälaidan mukaan. Nimittäin niillä riveillä, joissa on korkeita matemaattisia merkkejä (esim. vektori AB), lista-aakkosen heiluvat muuta riviä ylempänä. Esim. xyz-koordinaatisto tehtävä 9. 

Tää on nyt tällaista äärimmäistä pilkunviilausta ja voi olla selainkohtaista, mutta pistin nyt tänne kuitenkin, kun omaan silmään vähän sattui.

**Comment by ruumis** [comment]
nyt pitäisi olla korjattu

**Comment by LottaOinonen** [comment]
Hyvin korjattu! 

Huomasin kuitenkin taas uuden ominaisuuden: kapealla ruudulla alakohtien rivitys ei ole ihan kaunein, esim. xyz-koordinaatiston tehtävä 22. Tää on tämmöistä superpilkunviilausta..
