### ISSUE TITLE
Euron merkki ei toimi

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#32]
Yritin ottaa eurosym-paketin käyttöön, mutta \euro ei toimi kuitenkaan.

**Comment by ruumis** [comment]
Kelpaako pelkkä € merkki? Sen saa myös latexiin \unicode{0x20AC}, mutta €:kin toimii.

http://kisallioppiminen.fi/kurssit/testi/
https://github.com/kisallioppiminen/kisallioppiminen.github.io/blob/master/kurssit/testi/index.html

**Comment by LottaOinonen** [comment]
Testasin ja tuo unicode-juttu oli juuri se, mitä tarvitsin :)
