### ISSUE TITLE
numerointi tulostettavassa versiossa MAY1

### ISSUE THREAD

**Issue by pnissine** [kisallioppiminen/kisallioppiminen.github.io#37]
Ongelmia on kaksi:
1) numerointi ei täsmää oikein mitenkään nettimateriaaliin. Jos siis saisi joko jokaisen luvun erikseen tulostettavana versiona, jolloin ongelma kai poistuisi tai sitten jonkun muun ratkaisun, jotta numerointiin tulisi vähän enemmän tolkkua, esim. yhteiskuntatekstissä olevat kaksi tehtävää tekstin sisään ei-tehtävinä, jotta numerointi lähtee Luvut ja laskutoimitukset -kohdasta.
2) joku staattinen versio kurssin etusivulle, jotta sitä voi käyttää, jos ahdistaa, että nettiversio päivittyy.

**Comment by ruumis** [comment]
"jokaisen luvun erikseen tulostettavana versiona". jokaisen luvun voi tulostaa eli teen toisen vaihtoehdon.

**Comment by ruumis** [comment]
pdf lisätyy kurssin etusivulle
