### ISSUE TITLE
Erilaiset rivivälit kappaleissa ja listoissa

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#38]
Ainakin mulla (mac + chrome) listoissa on pienempi riviväli kuin tavallisessa kappaletekstissä. Selkeitä esimerkkejä esim. tehtävä 4.21 ja teoreema 9 (kunhan laittaa selaimen niin kapeaksi, että se ikäänkuin muistuttaa puhelimen näyttöä). Tää on sarjassa epäoleellisuuksia, mutta mitä sanot Thomas, pystyisikö jostain säätämään nuo rivivälit samoiksi sekä kappaleisiin että listoihin?

**Comment by ruumis** [comment]
Nyt on sama rivinväli kuin leipätekstissä
