### ISSUE TITLE
Teoreemojen nimet

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#41]
Moi!

Tuli mieleen, olisiko mahdollista saada teoreemoille sekä numerot että nimet? Tyyliin "Teoreema 4: Kosinilause". Ei mitenkään kriittistä, mutta voisi olla kiva varsinkin tässä geometriakurssissa, jossa on niin paljon nimettyjä tuloksia.

**Comment by LottaOinonen** [comment]
Moi,

tuli uusi idea tähän liittyen. Olisiko mahdollista tehdä teoreemaympäristöstä variaatio, jossa teoreemalle voisi antaa nimen, ja siihen perään tulisi automaattisesti suluissa (TEOREEMA [numero]), esimerkiksi seuraavasti:

PYTHAGORAAN LAUSE (TEOREEMA 3)

**Comment by ruumis** [comment]
Ei ehkä kaunein ratkaisu, mutta nyt mikäli teoreemalle haluaa nimen, niin lisäämällä div-tagiin id="[teoreeman nimi]" nimi tulee muodossa nimi (TEOREEMA numero). Esim. `<div class="theorem" id="Pythagoraan lause">`.

**Comment by LottaOinonen** [comment]
Toimii erinomaisesti! Kiitos paljon!
