### ISSUE TITLE
Isot välit määritelmissä ja perusteluissa listojen tapauksessa

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#42]
Taas tällainen vähän epäoleellinen ulkonäköjuttu: jos määritelmässä tai teoreeman perustelussa on lista, tulee siihen aika isoja välejä ennen ja jälkeen listan. Esimerkkinä kolmioiden yhdenmuotoisuuden määritelmä MAA3-kurssissa tehtävän 1.8 jälkeen. Voisikohan tätä jotenkin säätää?

**Comment by ruumis** [comment]
Pienennetty. Pitääkö vielä pienentää?

**Comment by LottaOinonen** [comment]
Mulla näkyy vieläkin tällaisena: 

![screen shot 2016-10-12 at 14 23 54](https://cloud.githubusercontent.com/assets/7556643/19308334/9e025834-9087-11e6-96ff-f005c980a1b0.png)

Onkohan jokin selaimeen liittyvä juttu?
