### ISSUE TITLE
MAA3: geogebrajuttuja

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#43]
Saisikohan Laurilta tästä geogebrasta version, jossa ei olisi mitään kirjaimia näkyvissä lopussa (saisivat miettiä itse) eikä lukisi MAB3? 🙂

https://www.geogebra.org/m/xTd47krM

**Comment by pnissine** [comment]
https://github.com/kisallioppiminen/kisallioppiminen.github.io/issues/43

Tuollainen tuli.

**Comment by pnissine** [comment]
väärä linkki: siis tässä: https://www.geogebra.org/m/eyFFfWAE
