### ISSUE TITLE
Kurssin etusivu

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#5]
Kurssin etusivulle voi minun puolestani tehdä jotain, jos ehtii. Se on nyt vähän hassun näköinen, kun tein sen jotenkin eri formaatilla kuin muut. Voisi siis muuttaa takaisin järkevän näköiseksi. Piialla on ehkä jotain näkemystä siihen, mitä informaatiota siihen tulee. Ehkäpä jotain siitä, mihin vektoreita käytetään? Siihen mulla on paljon ajatuksia.

**Comment by ruumis** [comment]
Tässä vähän vaihtoehtoja:<br/>
<a href="http://kisallioppiminen.fi/kurssit/vektorit_versio0/index.html">Sivunavigaatiolla</a><br />
<a href="http://kisallioppiminen.fi/kurssit/may1/">Yhteen pötköön</a>

**Comment by ruumis** [comment]
Tai sitten:
<a href="http://kisallioppiminen.fi/kurssit/may1/index2.html">Laatikoittain</a>

**Comment by LottaOinonen** [comment]
Tuo laatikoittain on mun suosikki. Mitä mieltä sinä ja Piia olette?

**Comment by pnissine** [comment]
Toivoin myös laatikoita :) 

Piia

Lähetetty iPhonesta

**Comment by ruumis** [comment]
Hyvä! Laatikot oli Piian idea. Onko lisätoiveita?

**Comment by LottaOinonen** [comment]
Ei tällä hetkellä. Ne laatikot voisi toteuttaa siellä vektorit-kurssin etusivulla (nyt siellä on vielä erilainen versio).
