### ISSUE TITLE
Määritelmät toimivat hyvin, teoreema kaipaa viilausta

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#6]
Moi,

määritelmän css-näyttää toimivan hyvin. Teoreemaa pitäisi vähän säätää. Ainakin teoreeman "Kaksi vektoria ovat samat, jos ja vain jos ne ovat samansuuntaiset ja yhtä pitkät" kohdalla sana "perustelu" on samalla värillä kuin teoreema itse. Ideana olisi, että sekin olisi sillä vaaleammalla värillä, jolla varsinainen perustelu on.

Jos tämä on hankala tehdä, voidaan keksiä jotain muutakin.

**Comment by ruumis** [comment]
Tein tuollaisen div class="proof":n, jonka sisälle perustelut tai todistukset tulevat

**Comment by LottaOinonen** [comment]
Näyttää hyvältä!
