### ISSUE TITLE
Suorat ja tasot: tehtävät eivät aukea

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#7]
Moi Thomas!

Suorat ja tasot välilehdellä tehtävät eivät aukea enkä tiedä, missä vika. Piialla samaa ongelmaa MAY:ssa. Tarkistaisitko asian sitten kun ehdit?

**Comment by LottaOinonen** [comment]
Ohjeisiin voisi lisätä, että tehtävän id:ssä ei saa olla pistettä

**Comment by ruumis** [comment]
lisätty
