### ISSUE TITLE
Tekstin leveys sivuilla?

### ISSUE THREAD

**Issue by LottaOinonen** [kisallioppiminen/kisallioppiminen.github.io#8]
Hei!

Huomasin, että vektorit-kurssin välilehdillä on useita eri sivuleveyksiä: xy-taso on tosi leveä, Geometriaa vektoreiden avulla vähän kapeampi, Suorat ja tasot tällä hetkellä tosi kapea. Onko teillä näkemystä, millainen olisi hyvä? Tällä ei kiirettä, mutta olisi kiva yhteinäistää jossain vaiheessa. Mun työskentelyä helpottaa, jos lopputuloksen visuaalisen toteutuksen pystyy näkemään, mutta pärjään kyllä ilmankin :) 

Tietokoneella Geometriaa vektoreiden avulla näyttää mun silmiin tällä hetkellä parhaalta.

Puhelimellani mikään leveyksistä ei toimi enää yhtä hyvin kuin ennen se leveä versio, koska marginaaleja ei ole missään versiossa ollenkaan.

Tabletilla levein eli xy-taso toimii, samoin Geometriaa vektoreiden avulla. Suorat ja tasot on liian kapea.

**Comment by ruumis** [comment]
Tämä johtuu korjauksista, joita tein.

Eli normaali (leveämpi) tulee jos 
    main-class: atop 
ja kapeampi (mahdollistaa sivunavigaation) jos
    main-class: aside

**Comment by LottaOinonen** [comment]
Joo, nyt on kivasti yhtenäinen ja koneella  + tabletilla hyvä, mutta puhelimella ei ole marginaaleja. En tiedä, onko väliä. Jätän tän nyt kuitenkin auki, pitää ehkä jutella yhdessä (tai jos päätätte, ettei välitetä puhelimista, niin sitten ok).

**Comment by ruumis** [comment]
Se poistaa ne marginaalit, koska puhelimen näyttö on niin kapea. Ne saa kyllä sinne.

**Comment by LottaOinonen** [comment]
Pienet marginaalit olisi kivat puhelimessakin. Nyt näyttää niin tukkoiselta kun melkein leikkautuu kesken.
